"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { LearningEngine, ProtocolEngine, StateEngine, type Protocol, type RecoveryWindow, type StateVector } from "@stateos/core";

const DIMS = ["attention", "clarity", "energy", "presence", "intentionality", "recovery", "adaptability"] as const;
type Dimension = typeof DIMS[number]; type Step = 1|2|3|4|5|6|7|8;
const LABEL: Record<Dimension,string> = { attention:"Attention", clarity:"Clarity", energy:"Energy", presence:"Presence", intentionality:"Intentionality", recovery:"Recovery", adaptability:"Adaptability" };
const OBJECTIVES = {
  "Pre-Keynote Presentation": { objective:"Prepare for a clear, focused and confident presentation.", requiredState:{attention:.84,clarity:.88,energy:.72,presence:.9,intentionality:.9,recovery:.62,adaptability:.76}, start:{attention:.58,clarity:.64,energy:.7,presence:.52,intentionality:.78,recovery:.42,adaptability:.62} },
  "Context Switching Recovery": { objective:"Recover cognitive clarity and presence after rapid context switching.", requiredState:{attention:.78,clarity:.84,energy:.66,presence:.86,intentionality:.78,recovery:.82,adaptability:.86}, start:{attention:.46,clarity:.48,energy:.54,presence:.42,intentionality:.56,recovery:.28,adaptability:.68} },
  "Deep Work": { objective:"Enter a sustained state for focused execution.", requiredState:{attention:.9,clarity:.88,energy:.72,presence:.86,intentionality:.92,recovery:.58,adaptability:.72}, start:{attention:.62,clarity:.66,energy:.64,presence:.58,intentionality:.72,recovery:.48,adaptability:.58} },
  "Difficult Conversation": { objective:"Prepare for a clear, present and intentional difficult conversation.", requiredState:{attention:.82,clarity:.86,energy:.68,presence:.92,intentionality:.9,recovery:.72,adaptability:.88}, start:{attention:.64,clarity:.6,energy:.58,presence:.5,intentionality:.74,recovery:.46,adaptability:.66} },
  "Cognitive De-escalation": { objective:"Reduce cognitive load and recover enough clarity to choose the next action.", requiredState:{attention:.68,clarity:.82,energy:.62,presence:.82,intentionality:.7,recovery:.9,adaptability:.82}, start:{attention:.42,clarity:.36,energy:.46,presence:.4,intentionality:.5,recovery:.24,adaptability:.6} },
} as const;
type Objective = keyof typeof OBJECTIVES; const KEY="stateos:mvp:sessions:v3";
const copy=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)); const pct=(v:number)=>`${Math.round(v*100)}%`; const delta=(v:number)=>`${v>=0?"+":"−"}${Math.abs(v*100).toFixed(0)}%`;
function protocolFor(name:Objective):Protocol{return{id:`demo-${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`,name,objective:OBJECTIVES[name].objective,targetDimensions:["attention","clarity","presence","intentionality"],minimumState:{recovery:.2},steps:[{id:"01",title:"Context isolation",instruction:"Identify the single outcome that matters and remove competing inputs.",durationSeconds:30,kind:"practice"},{id:"02",title:"Attention stabilization",instruction:"Return attention to the selected objective without following distraction.",durationSeconds:30,kind:"practice"},{id:"03",title:"Recovery window",instruction:"Pause and let cognitive load settle before choosing the next deliberate action.",durationSeconds:30,kind:"recovery"},{id:"04",title:"Intent reinforcement",instruction:"State the capability you need and the action you will take next.",durationSeconds:30,kind:"reflection"}]};}
interface History{id:string;objective:string;before:StateVector;after:StateVector;effectiveness:number;note:string;completedAt:string;}

export function StateSession(){
 const stateEngine=useMemo(()=>new StateEngine(),[]), protocolEngine=useMemo(()=>new ProtocolEngine(),[]), learningEngine=useMemo(()=>new LearningEngine(),[]);
 const [step,setStep]=useState<Step>(1),[objective,setObjective]=useState<Objective>("Pre-Keynote Presentation"),[current,setCurrent]=useState<StateVector>(copy(OBJECTIVES["Pre-Keynote Presentation"].start)),[after,setAfter]=useState<StateVector>(copy(OBJECTIVES["Pre-Keynote Presentation"].start)),[selected,setSelected]=useState<Protocol|null>(null),[protocolIndex,setProtocolIndex]=useState(0),[remaining,setRemaining]=useState(0),[running,setRunning]=useState(false),[recovery,setRecovery]=useState<RecoveryWindow|null>(null),[reflection,setReflection]=useState(""),[effectiveness,setEffectiveness]=useState(.7),[history,setHistory]=useState<History[]>([]),[status,setStatus]=useState("Ready"),[error,setError]=useState("");
 const completionGuard=useRef(false),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null); const required=OBJECTIVES[objective].requiredState,assessment=stateEngine.assess(current),gap=stateEngine.transition(current,required),transition=stateEngine.transition(current,after),protocol=selected??protocolFor(objective),active=protocol.steps[protocolIndex];
 const hasProgress=step>1||selected!==null||running||reflection.length>0;
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setHistory(JSON.parse(raw));}catch{setHistory([]);}},[]); useEffect(()=>()=>{if(timerRef.current)clearTimeout(timerRef.current);},[]);
 const reset=useCallback((name:Objective)=>{if(timerRef.current)clearTimeout(timerRef.current);setObjective(name);setCurrent(copy(OBJECTIVES[name].start));setAfter(copy(OBJECTIVES[name].start));setSelected(null);setProtocolIndex(0);setRemaining(0);setRunning(false);setRecovery(null);setReflection("");setEffectiveness(.7);setError("");completionGuard.current=false;setStep(1);setStatus(`Demo preset loaded: ${name}`);},[]);
 const changePreset=(name:Objective)=>{if(name===objective)return;if(hasProgress&&!window.confirm("This will discard the active transition and reset the session. Continue?"))return;reset(name);}; const goBack=(target:Step)=>{if(target<step&&!running)setStep(target);};
 const update=(k:Dimension,v:number)=>setCurrent(s=>({...s,[k]:v})),updateAfter=(k:Dimension,v:number)=>setAfter(s=>({...s,[k]:v}));
 const chooseProtocol=()=>{try{const match=protocolEngine.match({objective:OBJECTIVES[objective].objective,requiredState:required},current,[protocolFor(objective)]);setSelected(match.protocol);setProtocolIndex(0);setStatus(`Protocol matched at ${Math.round(match.score*100)}%.`);setStep(4);setError("");}catch(e){setError(e instanceof Error?e.message:"Protocol match failed.");}};
 const finishExecution=useCallback(()=>{if(completionGuard.current||!active)return;completionGuard.current=true;setRunning(false);setRemaining(0);if(active.kind==="recovery"){const rw=protocolEngine.recoveryWindow(active.durationSeconds,active.instruction);rw.completed=true;setRecovery(rw);}if(protocolIndex<protocol.steps.length-1){setProtocolIndex(i=>i+1);completionGuard.current=false;setStatus("Step complete. Continue the protocol.");}else{setStep(6);setStatus("Protocol complete. Reassess the resulting state.");}},[active,protocolIndex,protocol.steps.length,protocolEngine]);
 useEffect(()=>{if(!running||remaining<=0)return;timerRef.current=setTimeout(()=>setRemaining(v=>Math.max(0,v-1)),1000);return()=>{if(timerRef.current)clearTimeout(timerRef.current);};},[running,remaining]); useEffect(()=>{if(running&&remaining===0)finishExecution();},[running,remaining,finishExecution]);
 const startStep=()=>{if(!active)return;completionGuard.current=false;if(active.kind==="recovery"&&!recovery)setRecovery(protocolEngine.recoveryWindow(active.durationSeconds,active.instruction));setRemaining(active.durationSeconds);setRunning(true);setStep(5);setStatus(`Executing: ${active.title}`);};
 const complete=async()=>{const item:History={id:crypto.randomUUID(),objective:OBJECTIVES[objective].objective,before:current,after,effectiveness,note:reflection.trim(),completedAt:new Date().toISOString()};const next=[item,...history].slice(0,50);setHistory(next);localStorage.setItem(KEY,JSON.stringify(next));const baseline=learningEngine.adaptBaseline({vector:current,sampleCount:history.length,updatedAt:new Date().toISOString()},after);try{const r=await fetch("/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",sessionId:item.id,objective:item.objective,currentState:current,requiredState:required,afterState:after,reflection:{note:item.note||"No written reflection.",effectiveness},snapshots:next.map(x=>({id:x.id,capturedAt:x.completedAt,vector:x.after,context:x.objective})),baseline})});if(!r.ok)throw new Error("Session API rejected the completion payload.");setStatus("Transition recorded and LearningEngine updated.");}catch(e){setError(e instanceof Error?e.message:"API dispatch failed; local history retained.");setStatus("Transition saved locally; server dispatch needs retry.");}setStep(8);};
 const labels=["Observe","Interpret","Intent","Select","Execute","Reassess","Reflect","Adapt"];
 return <main className="stateos-shell"><header className="stateos-topbar"><div><div className="brand-mark">STATE<span>OS</span></div><div className="system-label">STATE TRANSITION SESSION · HARDENED DEMO</div></div><div className="demo-controls"><label>Demo mode<select value={objective} onChange={e=>changePreset(e.target.value as Objective)}>{(Object.keys(OBJECTIVES) as Objective[]).map(n=><option key={n}>{n}</option>)}</select></label><div className="step-chip">{String(step).padStart(2,"0")} / 08</div></div></header><section className="session-intro"><div><p className="eyebrow">State Transition Session</p><h1>Move from the state you are in toward the state you need.</h1><p className="lead">Observe → interpret → intend → select → execute → reassess → reflect → adapt.</p></div><div className="status-card"><span>SESSION STATUS</span><strong>{status}</strong><small>{history.length} completed transition{history.length===1?"":"s"} stored locally</small></div></section><nav className="lifecycle" aria-label="Session lifecycle">{labels.map((label,i)=>{const n=(i+1) as Step;return <button key={label} className={step===n?"active":step>n?"done":""} disabled={running||n>step} onClick={()=>goBack(n)}>{String(n).padStart(2,"0")}<span>{label}</span></button>;})}</nav>{error&&<div className="error-banner">{error}</div>}
 {step===1&&<section className="workspace"><div className="workspace-head"><div><p className="eyebrow">01 · Observe</p><h2>Current State</h2><p>Calibrate the starting vector. Values are bounded from 0 to 1.</p></div><div className="metric"><span>CAPACITY</span><strong>{pct(assessment.mean)}</strong><small>{LABEL[assessment.strongest]} strongest · {LABEL[assessment.weakest]} weakest</small></div></div><div className="dimension-grid">{DIMS.map(k=><label className="dimension" key={k}><span><b>{LABEL[k]}</b><em>{pct(current[k])}</em></span><input type="range" min="0" max="1" step=".01" value={current[k]} onChange={e=>update(k,Number(e.target.value))}/><i>{current[k]<.4?"Constrained":current[k]<.7?"Available":"Strong"}</i></label>)}</div><div className="diagnostics"><div><span>Mean capacity</span><strong>{pct(assessment.mean)}</strong></div><div><span>Largest required gap</span><strong>{LABEL[DIMS.reduce((a,b)=>Math.abs(required[b]-current[b])>Math.abs(required[a]-current[a])?b:a)]}</strong></div><div><span>Gap movement</span><strong>{gap.direction} · {gap.meanAbsoluteDelta.toFixed(2)}</strong></div></div><button className="primary" onClick={()=>setStep(2)}>Interpret current state →</button></section>}
 {step===2&&<section className="workspace compact"><p className="eyebrow">02 · Interpret</p><h2>Read the current configuration.</h2><p className="lead-sm">The vector is a starting condition, not a score. The weakest dimension and the distance to the required state guide the next decision.</p><div className="interpret-grid"><div><span>Capacity</span><strong>{pct(assessment.mean)}</strong></div><div><span>Constraint</span><strong>{LABEL[assessment.weakest]}</strong></div><div><span>Required direction</span><strong>{gap.direction}</strong></div></div><button className="primary" onClick={()=>setStep(3)}>Define intent →</button></section>}
 {step===3&&<section className="workspace"><p className="eyebrow">03 · Intent</p><h2>What capability does the situation require?</h2><div className="objective-grid">{(Object.keys(OBJECTIVES) as Objective[]).map(n=><button key={n} className={n===objective?"objective active":"objective"} onClick={()=>{setObjective(n);setAfter(copy(OBJECTIVES[n].start));}}><span>{n}</span><small>{OBJECTIVES[n].objective}</small></button>)}</div><div className="target-preview"><span>Required state</span><div>{DIMS.map(k=><div key={k}><b>{LABEL[k]}</b><strong>{pct(required[k])}</strong><div className="bar"><i style={{width:`${required[k]*100}%`}}/></div></div>)}</div></div><button className="primary" onClick={()=>setStep(4)}>Calculate gap →</button></section>}
 {step===4&&<section className="workspace"><p className="eyebrow">04 · Select</p><h2>State gap and protocol.</h2><div className="gap-table">{DIMS.map(k=>{const d=required[k]-current[k];return <div key={k}><span>{LABEL[k]}</span><strong className={d>=0?"positive":"negative"}>{delta(d)}</strong><div className="gap-track"><i style={{left:`${current[k]*100}%`}}/><b style={{left:`${required[k]*100}%`}}/></div></div>})}</div><div className="protocol-card"><div><span className="tag">MATCHED PROTOCOL</span><h3>{protocol.name}</h3><p>{protocol.objective}</p></div><div className="match-score">{Math.round(protocolEngine.match({objective:OBJECTIVES[objective].objective,requiredState:required},current,[protocol]).score*100)}%<small>match</small></div></div><button className="primary" onClick={chooseProtocol}>Confirm protocol →</button></section>}
 {step===5&&<section className="workspace execution"><div className="execution-top"><div><p className="eyebrow">05 · Execute</p><h2>{active?.title}</h2><p>{active?.instruction}</p></div><div className="timer">{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}<small>{active?.kind}{recovery&&active.kind==="recovery"?" · RecoveryWindow":""}</small></div></div><div className="progress-track"><i style={{width:`${((protocolIndex+(running?0:1))/protocol.steps.length)*100}%`}}/></div><div className="execution-actions">{running?<button className="primary" onClick={()=>{setRunning(false);setStatus("Execution paused.")}}>Pause</button>:<button className="primary" onClick={startStep}>{remaining>0?"Resume":"Start timed step"} →</button>}<span>Step {protocolIndex+1} of {protocol.steps.length}</span></div>{recovery&&<div className="recovery"><span>RECOVERY WINDOW</span><strong>{recovery.completed?"Completed":"Active"}</strong><p>{recovery.reason}</p></div>}</section>}
 {step===6&&<section className="workspace"><p className="eyebrow">06 · Reassess</p><h2>Measure the resulting state.</h2><p>Report the state you can honestly observe after the protocol.</p><div className="dimension-grid">{DIMS.map(k=><label className="dimension" key={k}><span><b>{LABEL[k]}</b><em>{pct(after[k])}</em></span><input type="range" min="0" max="1" step=".01" value={after[k]} onChange={e=>updateAfter(k,Number(e.target.value))}/><i>{delta(after[k]-current[k])} transition</i></label>)}</div><div className="diagnostics"><div><span>Euclidean movement</span><strong>{transition.euclideanDistance.toFixed(3)}</strong></div><div><span>Mean capacity change</span><strong>{delta(transition.capacityChange)}</strong></div><div><span>Mean absolute movement</span><strong>{transition.meanAbsoluteDelta.toFixed(3)}</strong></div></div><button className="primary" onClick={()=>setStep(7)}>Reflect →</button></section>}
 {step===7&&<section className="workspace"><p className="eyebrow">07 · Reflect</p><h2>What did the transition teach you?</h2><div className="reflection-grid"><label>Reflection<textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="What worked? Where was there friction? What should be repeated or changed?"/></label><label>Effectiveness<output>{pct(effectiveness)}</output><input type="range" min="0" max="1" step=".05" value={effectiveness} onChange={e=>setEffectiveness(Number(e.target.value))}/></label></div><div className="summary-line"><span>Capacity change</span><strong>{delta(transition.capacityChange)}</strong><span>Movement {transition.euclideanDistance.toFixed(3)}</span></div><button className="primary" onClick={complete}>Complete & adapt baseline →</button></section>}
 {step===8&&<section className="workspace completion"><div className="completion-mark">✓</div><p className="eyebrow">08 · Adapt</p><h2>Transition recorded.</h2><p className="lead-sm">The completed session is stored locally and dispatched to the LearningEngine API boundary.</p><div className="completion-grid"><div><span>Before</span><strong>{pct(stateEngine.assess(current).mean)}</strong></div><div><span>After</span><strong>{pct(stateEngine.assess(after).mean)}</strong></div><div><span>Capacity Δ</span><strong>{delta(transition.capacityChange)}</strong></div><div><span>Effectiveness</span><strong>{pct(effectiveness)}</strong></div></div><div className="history"><h3>Recent transitions</h3>{history.slice(0,5).map(h=><div className="history-row" key={h.id}><span>{new Date(h.completedAt).toLocaleString()}</span><b>{h.objective}</b><em>{pct(h.effectiveness)}</em></div>)}</div><button className="primary" onClick={()=>reset(objective)}>Run another transition →</button></section>}
 </main>;
}
